### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by egorbarkovsky** [evernote/iwana#7]
Hey! Is that great library alive?

**Comment by egorbarkovsky** [comment]
@akhaku @kohlschuetter @vRallev @ilias-t

**Comment by akhaku** [comment]
I think Ilias might still be at Evernote, but the rest of us haven't worked there in a number of years.

**Comment by kohlschuetter** [comment]
Hello there. I am the original author. I haven't touched the code since I left Evernote. However, it's open-source, and as long as you see some utility in it, please do keep using it. Since it's Apache 2.0 licensed, a fork could be an alternative if no-one at Evernote is interested in maintaining this repo.

**Comment by egorbarkovsky** [comment]
I got it, thanks a lot for the answers
